const initialRegionsState = {
  barreiroPrice: '',
  barreiroTime: '',
  centroSulPrice: '',
  centroSulTime: '',
  lestePrice: '',
  lesteTime: '',
  nordestePrice: '',
  nordesteTime: '',
  noroestePrice: '',
  noroesteTime: '',
  nortePrice: '',
  norteTime: '',
  oestePrice: '',
  oesteTime: '',
  pampulhaPrice: '',
  pampulhaTime: '',
  vendaNovaPrice: '',
  vendaNovaTime: '',
};
