const initialState = {
  street: '',
  streetNumber: '',
  district: '',
  complement: '',
  postalCode: '',
  city: '',
  state: '',
  expires: '',
  CVV: '',
  name: '',
  cpf: '',
  birth: new Date(),
  phone: '',
  cardNumber: '',
  paymentData: '',
  hash: '',
  page: 0,
  cardToken: '',
  cardBrand: '',
  products: [],
  subTotal: 0,
};

export default initialState;
